name: Concurrency Demo

on: 
    workflow_dispatch:

jobs:
    job_1:
      runs-on: ubuntu-latest
      steps:
        - name: test step
          run: echo "Hello!"

    job_2:
      runs-on: ubuntu-latest
      concurrency:
        group: prod-deploy
        cancel-in-progress: true
      steps:
        - name: Sleep loong for 600s
          run: sleep 600