name: Matrix workflow

on: 
    workflow_dispatch: 

jobs:
  job_1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker info on ${{ matrix.os }}
        run: docker info
      
      - name: Run ${{ matrix.images }}
        run: docker run ${{ matrix.images }}