name: Multi-Job Workflow

on: 
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout repo
          uses: actions/checkout@v4  
        
        - name: list and read file
          run: | 
            echo "My demo action!"
            ls -ltra
            cat README.md

        - name: Generate artwork
          run: |
            sudo apt install cowsay -y
            cowsay -f dragon "Run IDIOT....!" > dragon.txt

            
            
    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1

        steps:
            - name: test
              run: echo "from test job"
        
    deploy_job_3:
        runs-on: ubuntu-latest
        needs: [ test_job_2]
        steps:
        - name: test deploy
          run: echo "deploy step"