# name: Test running shell script

# on: push

# jobs:
#     script-job:
            
#         runs-on: ubuntu-latest

#         steps:      
#         - name: checkout code
#           uses: actions/checkout@v5

#         - name: list files
#           run: ls -ltra

#         - name: run script
#           run: | 
#             chmod +x script.sh
#             ./script.sh
          